name: Deploy .NET 8 API

on:
  push:
    branches: [master, main] # Chạy trên cả 2 nhánh cho chắc chắn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish API
        # Tìm file csproj bất kể nó nằm ở đâu và build vào folder 'out'
        run: dotnet publish **/DevBlog.API.csproj -c Release -o out /p:UseAppHost=false

      - name: Verify Build (Debug)
        run: ls -R out

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/*"
          target: "/home/nhatdev/apps/api/publish"
          strip_components: 1
          overwrite: true
          rm: true

      - name: Restart API Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo chown -R root:root /home/nhatdev/apps/api/publish
            sudo systemctl daemon-reload
            sudo systemctl restart devblog-api.service
            echo "Kiem tra file sau khi deploy:"
            ls -l /home/nhatdev/apps/api/publish/DevBlog.API.dll
